apiVersion: apps/v1
kind: Deployment
metadata:
  name: mnist-web-server
  namespace: tarik-nassar
  labels:
    app: mnist-web-server
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mnist-web-server
  template:
    metadata:
      labels:
        app: mnist-web-server
    spec:
      terminationGracePeriodSeconds: 30
      containers:
        - name: mnist-web-server
          image: {{REGISTRY_URL}}/{{IMG_NAME}}
          port: 7070
---
apiVersion: v1
kind: Service
metadata:
  name: mnist-web-server-service
spec:
  selector:
    app: mnist-web-server
  ports:
    - port: 7070
      targetPort: 7070
